/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abhidesai
 */
import java.util.ArrayList;
import java.util.Calendar;
public class CourseSchedulerGUI extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    private String currentSemester; 
    
    public CourseSchedulerGUI() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildStudentComboBoxes();
    }
    
    public void rebuildSemesterComboBoxes()
    {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        changeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0)
        {
            currentSemesterLabel2.setText(semesters.get(0));
            currentSemester = semesters.get(0);
        }
        else
        {
            currentSemesterLabel2.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    
    
    public void rebuildCourseComboBoxes()
    {
        ArrayList<String> courses = CourseQueries.getAllCourseCodes(currentSemester);
        studentScheduleCourseComboBox1.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        studentDropCourseComboBox1.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        adminCourseListComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        adminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
    }
    //should display userID
    public void rebuildStudentComboBoxes()
    {
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        ArrayList<String> studentNames = new ArrayList<>();
        
        for (StudentEntry student:students)
        {
            String name = student.getFirstName() + " " + student.getLastName() + " " + student.getStudentID();
             
            studentNames.add(name);
        }
        studentScheduleCourseComboBox2.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        studentDisplayCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        adminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        studentDropCourseComboBox2.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
    }
    
    

    /**
     * Creates new form CourseSchedulerGUI
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        currentSemesterLabel1 = new javax.swing.JLabel();
        changeSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        currentSemesterLabel2 = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        adminPanel = new javax.swing.JPanel();
        adminTabbedPane = new javax.swing.JTabbedPane();
        adminAddSemesterPanel = new javax.swing.JPanel();
        adminSemesterNameLabel = new javax.swing.JLabel();
        adminSemesterNameTextField = new javax.swing.JTextField();
        adminSemesterSubmitButton = new javax.swing.JButton();
        adminSemesterStatusLabel = new javax.swing.JLabel();
        adminAddStudentPanel = new javax.swing.JPanel();
        adminStudentIDLabel = new javax.swing.JLabel();
        adminStudentIDTextField = new javax.swing.JTextField();
        adminStudentFirstNameLabel = new javax.swing.JLabel();
        adminStudentFirstNameTextField = new javax.swing.JTextField();
        adminStudentLastNameLabel = new javax.swing.JLabel();
        adminStudentLastNameTextField = new javax.swing.JTextField();
        adminStudentSubmitButton = new javax.swing.JButton();
        adminStudentStatusLabel = new javax.swing.JLabel();
        adminAddCoursePanel = new javax.swing.JPanel();
        adminCourseCodeLabel = new javax.swing.JLabel();
        adminCourseCodeTextfield = new javax.swing.JTextField();
        adminCourseDescriptionLabel = new javax.swing.JLabel();
        adminCourseDescriptionTextField = new javax.swing.JTextField();
        adminCourseSeatsLabel = new javax.swing.JLabel();
        adminCourseSeatsSpinner = new javax.swing.JSpinner();
        adminCourseSubmitButton = new javax.swing.JButton();
        adminCourseStatusLabel = new javax.swing.JLabel();
        adminDisplayCourseListPanel = new javax.swing.JPanel();
        adminCourseListLabel = new javax.swing.JLabel();
        adminCourseListComboBox = new javax.swing.JComboBox<>();
        adminCourseListDisplayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminCourseListScheduledTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminCourseListWaitlistTextArea = new javax.swing.JTextArea();
        adminCourseListScheduledLabel = new javax.swing.JLabel();
        adminCourseListWaitlistLabel = new javax.swing.JLabel();
        adminDropStudentPanel = new javax.swing.JPanel();
        adminDropStudentLabel = new javax.swing.JLabel();
        adminDropStudentComboBox = new javax.swing.JComboBox<>();
        adminDropStudentButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminDropStudentTextArea = new javax.swing.JTextArea();
        adminDropCoursePanel = new javax.swing.JPanel();
        adminDropCourseLabel = new javax.swing.JLabel();
        adminDropCourseComboBox = new javax.swing.JComboBox<>();
        adminDropCourseButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        adminDropCourseTextArea = new javax.swing.JTextArea();
        studentPanel = new javax.swing.JPanel();
        studentTabbedPane = new javax.swing.JTabbedPane();
        studentDisplayCoursesPanel = new javax.swing.JPanel();
        studentDisplayCoursesButton = new javax.swing.JButton();
        studentDisplayScrollPane = new javax.swing.JScrollPane();
        studentDisplayCourseTextArea = new javax.swing.JTextArea();
        studentScheduleCoursesPanel = new javax.swing.JPanel();
        studentScheduleCourseLabel = new javax.swing.JLabel();
        studentScheduleCourseComboBox1 = new javax.swing.JComboBox<>();
        studentScheduleCourseComboBox2 = new javax.swing.JComboBox<>();
        studentScheduleCourseStudentLable = new javax.swing.JLabel();
        studentScheduleCourseButton = new javax.swing.JButton();
        studentScheduleCourseStatusLabel = new javax.swing.JLabel();
        studentDisplaySchedulePanel = new javax.swing.JPanel();
        studentDisplayCourseLabel = new javax.swing.JLabel();
        studentDisplayCourseComboBox = new javax.swing.JComboBox<>();
        studentDisplayScheduleButton = new javax.swing.JButton();
        studentAddCourseScrollPane = new javax.swing.JScrollPane();
        studentDisplayScheduleTextArea = new javax.swing.JTextArea();
        studentDropCoursePanel = new javax.swing.JPanel();
        studentDropCourseLabel1 = new javax.swing.JLabel();
        studentDropCourseComboBox1 = new javax.swing.JComboBox<>();
        studentDropCourseButton = new javax.swing.JButton();
        studentDropCourseLabel2 = new javax.swing.JLabel();
        studentDropCourseComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        studentDropCourseTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(28, 66, 124));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setRequestFocusEnabled(false);

        currentSemesterLabel1.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 18)); // NOI18N
        currentSemesterLabel1.setText("Current Semester:");

        changeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        currentSemesterLabel2.setText("None");

        adminSemesterNameLabel.setText("Semester Name:");

        adminSemesterSubmitButton.setText("Submit");
        adminSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSemesterSubmitButtonActionPerformed(evt);
            }
        });

        adminSemesterStatusLabel.setText("             ");

        javax.swing.GroupLayout adminAddSemesterPanelLayout = new javax.swing.GroupLayout(adminAddSemesterPanel);
        adminAddSemesterPanel.setLayout(adminAddSemesterPanelLayout);
        adminAddSemesterPanelLayout.setHorizontalGroup(
            adminAddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddSemesterPanelLayout.createSequentialGroup()
                .addComponent(adminSemesterSubmitButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(adminAddSemesterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminAddSemesterPanelLayout.createSequentialGroup()
                        .addComponent(adminSemesterNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminSemesterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        adminAddSemesterPanelLayout.setVerticalGroup(
            adminAddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddSemesterPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(adminAddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminSemesterNameLabel)
                    .addComponent(adminSemesterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminSemesterSubmitButton)
                .addGap(38, 38, 38)
                .addComponent(adminSemesterStatusLabel)
                .addGap(0, 122, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Add Semester", adminAddSemesterPanel);

        adminStudentIDLabel.setText("Student ID:");

        adminStudentFirstNameLabel.setText("First Name:");

        adminStudentLastNameLabel.setText("Last Name:");

        adminStudentSubmitButton.setText("Submit");
        adminStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminStudentSubmitButtonActionPerformed(evt);
            }
        });

        adminStudentStatusLabel.setText("   ");

        javax.swing.GroupLayout adminAddStudentPanelLayout = new javax.swing.GroupLayout(adminAddStudentPanel);
        adminAddStudentPanel.setLayout(adminAddStudentPanelLayout);
        adminAddStudentPanelLayout.setHorizontalGroup(
            adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                        .addComponent(adminStudentFirstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                        .addComponent(adminStudentLastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminStudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                        .addComponent(adminStudentIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminStudentSubmitButton)
                    .addComponent(adminStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        adminAddStudentPanelLayout.setVerticalGroup(
            adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentIDLabel)
                    .addComponent(adminStudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentFirstNameLabel)
                    .addComponent(adminStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminAddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminStudentLastNameLabel)
                    .addComponent(adminStudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminStudentSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Add Student", adminAddStudentPanel);

        adminCourseCodeLabel.setText("Course Code:");

        adminCourseCodeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseCodeTextfieldActionPerformed(evt);
            }
        });

        adminCourseDescriptionLabel.setText("Course Description:");

        adminCourseDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseDescriptionTextFieldActionPerformed(evt);
            }
        });

        adminCourseSeatsLabel.setText("Seats:");

        adminCourseSubmitButton.setText("Submit");
        adminCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseSubmitButtonActionPerformed(evt);
            }
        });

        adminCourseStatusLabel.setText("     ");

        javax.swing.GroupLayout adminAddCoursePanelLayout = new javax.swing.GroupLayout(adminAddCoursePanel);
        adminAddCoursePanel.setLayout(adminAddCoursePanelLayout);
        adminAddCoursePanelLayout.setHorizontalGroup(
            adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addComponent(adminCourseCodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminCourseCodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addComponent(adminCourseDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                        .addComponent(adminCourseSeatsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminCourseSubmitButton)
                    .addComponent(adminCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        adminAddCoursePanelLayout.setVerticalGroup(
            adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminAddCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminCourseCodeLabel)
                    .addComponent(adminCourseCodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminCourseDescriptionLabel)
                    .addComponent(adminCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminAddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminCourseSeatsLabel)
                    .addComponent(adminCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminCourseSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(adminCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Add Course", adminAddCoursePanel);

        adminCourseListLabel.setText("Selected Course:");

        adminCourseListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adminCourseListDisplayButton.setText("Display");
        adminCourseListDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseListDisplayButtonActionPerformed(evt);
            }
        });

        adminCourseListScheduledTextArea.setColumns(20);
        adminCourseListScheduledTextArea.setRows(5);
        jScrollPane1.setViewportView(adminCourseListScheduledTextArea);

        adminCourseListWaitlistTextArea.setColumns(20);
        adminCourseListWaitlistTextArea.setRows(5);
        jScrollPane2.setViewportView(adminCourseListWaitlistTextArea);

        adminCourseListScheduledLabel.setText("Scheduled:");

        adminCourseListWaitlistLabel.setText("Waitlisted:");

        javax.swing.GroupLayout adminDisplayCourseListPanelLayout = new javax.swing.GroupLayout(adminDisplayCourseListPanel);
        adminDisplayCourseListPanel.setLayout(adminDisplayCourseListPanelLayout);
        adminDisplayCourseListPanelLayout.setHorizontalGroup(
            adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                        .addComponent(adminCourseListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminCourseListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(adminCourseListDisplayButton))
                    .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                        .addGroup(adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminCourseListScheduledLabel))
                        .addGap(73, 73, 73)
                        .addGroup(adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminCourseListWaitlistLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        adminDisplayCourseListPanelLayout.setVerticalGroup(
            adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                        .addComponent(adminCourseListWaitlistLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminDisplayCourseListPanelLayout.createSequentialGroup()
                        .addGroup(adminDisplayCourseListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminCourseListLabel)
                            .addComponent(adminCourseListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminCourseListDisplayButton))
                        .addGap(13, 13, 13)
                        .addComponent(adminCourseListScheduledLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Display Course List", adminDisplayCourseListPanel);

        adminDropStudentLabel.setText("Select Student:");

        adminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adminDropStudentButton.setText("Drop Student");
        adminDropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDropStudentButtonActionPerformed(evt);
            }
        });

        adminDropStudentTextArea.setColumns(20);
        adminDropStudentTextArea.setRows(5);
        jScrollPane3.setViewportView(adminDropStudentTextArea);

        javax.swing.GroupLayout adminDropStudentPanelLayout = new javax.swing.GroupLayout(adminDropStudentPanel);
        adminDropStudentPanel.setLayout(adminDropStudentPanelLayout);
        adminDropStudentPanelLayout.setHorizontalGroup(
            adminDropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDropStudentPanelLayout.createSequentialGroup()
                .addGroup(adminDropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDropStudentPanelLayout.createSequentialGroup()
                        .addComponent(adminDropStudentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminDropStudentButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 508, Short.MAX_VALUE))
        );
        adminDropStudentPanelLayout.setVerticalGroup(
            adminDropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDropStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminDropStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDropStudentLabel)
                    .addComponent(adminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDropStudentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Drop Student", adminDropStudentPanel);

        adminDropCourseLabel.setText(" Select Course:");

        adminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adminDropCourseButton.setText("Drop Course");
        adminDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDropCourseButtonActionPerformed(evt);
            }
        });

        adminDropCourseTextArea.setColumns(20);
        adminDropCourseTextArea.setRows(5);
        jScrollPane4.setViewportView(adminDropCourseTextArea);

        javax.swing.GroupLayout adminDropCoursePanelLayout = new javax.swing.GroupLayout(adminDropCoursePanel);
        adminDropCoursePanel.setLayout(adminDropCoursePanelLayout);
        adminDropCoursePanelLayout.setHorizontalGroup(
            adminDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDropCoursePanelLayout.createSequentialGroup()
                .addComponent(adminDropCourseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDropCourseButton)
                .addGap(0, 524, Short.MAX_VALUE))
            .addGroup(adminDropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminDropCoursePanelLayout.setVerticalGroup(
            adminDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDropCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDropCourseLabel)
                    .addComponent(adminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDropCourseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Drop Course", adminDropCoursePanel);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminTabbedPane)
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Admin", adminPanel);

        studentDisplayCoursesPanel.setPreferredSize(new java.awt.Dimension(1000, 400));

        studentDisplayCoursesButton.setText("Display");
        studentDisplayCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDisplayCoursesButtonActionPerformed(evt);
            }
        });

        studentDisplayCourseTextArea.setColumns(20);
        studentDisplayCourseTextArea.setRows(5);
        studentDisplayScrollPane.setViewportView(studentDisplayCourseTextArea);

        javax.swing.GroupLayout studentDisplayCoursesPanelLayout = new javax.swing.GroupLayout(studentDisplayCoursesPanel);
        studentDisplayCoursesPanel.setLayout(studentDisplayCoursesPanelLayout);
        studentDisplayCoursesPanelLayout.setHorizontalGroup(
            studentDisplayCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplayCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentDisplayCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentDisplayCoursesButton)
                    .addComponent(studentDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        studentDisplayCoursesPanelLayout.setVerticalGroup(
            studentDisplayCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplayCoursesPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(studentDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentDisplayCoursesButton)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        studentTabbedPane.addTab("Display Courses", studentDisplayCoursesPanel);

        studentScheduleCourseLabel.setText("Select Course:");

        studentScheduleCourseComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studentScheduleCourseComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studentScheduleCourseStudentLable.setText("Select Student:");

        studentScheduleCourseButton.setText("Submit");
        studentScheduleCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentScheduleCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentScheduleCoursesPanelLayout = new javax.swing.GroupLayout(studentScheduleCoursesPanel);
        studentScheduleCoursesPanel.setLayout(studentScheduleCoursesPanelLayout);
        studentScheduleCoursesPanelLayout.setHorizontalGroup(
            studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentScheduleCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentScheduleCourseStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(studentScheduleCoursesPanelLayout.createSequentialGroup()
                .addGroup(studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentScheduleCoursesPanelLayout.createSequentialGroup()
                        .addGroup(studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentScheduleCourseLabel)
                            .addComponent(studentScheduleCourseStudentLable))
                        .addGap(25, 25, 25)
                        .addGroup(studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentScheduleCourseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentScheduleCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(studentScheduleCourseButton))
                .addGap(0, 620, Short.MAX_VALUE))
        );
        studentScheduleCoursesPanelLayout.setVerticalGroup(
            studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentScheduleCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentScheduleCourseLabel)
                    .addComponent(studentScheduleCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentScheduleCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentScheduleCourseStudentLable)
                    .addComponent(studentScheduleCourseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentScheduleCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentScheduleCourseStatusLabel)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        studentTabbedPane.addTab("Schedule Courses", studentScheduleCoursesPanel);

        studentDisplayCourseLabel.setText("Select Student:");

        studentDisplayCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studentDisplayScheduleButton.setText("Display");
        studentDisplayScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDisplayScheduleButtonActionPerformed(evt);
            }
        });

        studentDisplayScheduleTextArea.setColumns(20);
        studentDisplayScheduleTextArea.setRows(5);
        studentAddCourseScrollPane.setViewportView(studentDisplayScheduleTextArea);

        javax.swing.GroupLayout studentDisplaySchedulePanelLayout = new javax.swing.GroupLayout(studentDisplaySchedulePanel);
        studentDisplaySchedulePanel.setLayout(studentDisplaySchedulePanelLayout);
        studentDisplaySchedulePanelLayout.setHorizontalGroup(
            studentDisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplaySchedulePanelLayout.createSequentialGroup()
                .addComponent(studentDisplayScheduleButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(studentDisplaySchedulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentDisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentAddCourseScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentDisplaySchedulePanelLayout.createSequentialGroup()
                        .addComponent(studentDisplayCourseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentDisplayCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        studentDisplaySchedulePanelLayout.setVerticalGroup(
            studentDisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDisplaySchedulePanelLayout.createSequentialGroup()
                .addGroup(studentDisplaySchedulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDisplayCourseLabel)
                    .addComponent(studentDisplayCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentAddCourseScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(studentDisplayScheduleButton)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        studentTabbedPane.addTab("Display Schedule", studentDisplaySchedulePanel);

        studentDropCourseLabel1.setText("Select Course:");

        studentDropCourseComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studentDropCourseButton.setText("Drop Course");
        studentDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDropCourseButtonActionPerformed(evt);
            }
        });

        studentDropCourseLabel2.setText("Select Student:");

        studentDropCourseComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        studentDropCourseTextArea.setColumns(20);
        studentDropCourseTextArea.setRows(5);
        jScrollPane5.setViewportView(studentDropCourseTextArea);

        javax.swing.GroupLayout studentDropCoursePanelLayout = new javax.swing.GroupLayout(studentDropCoursePanel);
        studentDropCoursePanel.setLayout(studentDropCoursePanelLayout);
        studentDropCoursePanelLayout.setHorizontalGroup(
            studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDropCoursePanelLayout.createSequentialGroup()
                .addGroup(studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentDropCourseButton)
                    .addGroup(studentDropCoursePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentDropCoursePanelLayout.createSequentialGroup()
                                .addComponent(studentDropCourseLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentDropCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(studentDropCoursePanelLayout.createSequentialGroup()
                                .addComponent(studentDropCourseLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentDropCourseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(504, Short.MAX_VALUE))
        );
        studentDropCoursePanelLayout.setVerticalGroup(
            studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDropCoursePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDropCourseLabel1)
                    .addComponent(studentDropCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentDropCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDropCourseComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentDropCourseLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentDropCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        studentTabbedPane.addTab("Drop Course", studentDropCoursePanel);

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addComponent(studentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Student", studentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(currentSemesterLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentSemesterLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeSemesterButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(269, 269, 269))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentSemesterLabel1)
                    .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(currentSemesterLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        String semester = changeSemesterComboBox.getSelectedItem().toString();
        currentSemesterLabel2.setText(semester);
        currentSemester = semester;
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void adminSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSemesterSubmitButtonActionPerformed
        String semester = adminSemesterNameTextField.getText();
        SemesterQueries.addSemester(semester);
        adminSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_adminSemesterSubmitButtonActionPerformed
//not needed accidentally added
    private void adminCourseDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCourseDescriptionTextFieldActionPerformed
 
    private void adminStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminStudentSubmitButtonActionPerformed
        String studentID = adminStudentIDTextField.getText();
        String studentFirstName = adminStudentFirstNameTextField.getText();
        String studentLastName = adminStudentLastNameTextField.getText();
        
        if (!studentID.matches("[0-9]+")) 
        {
            adminStudentStatusLabel.setText("Not a valid input. Please try again (numbers only)");
            return;
        }
        
    
        StudentEntry student = new StudentEntry(studentID, studentFirstName, studentLastName);
        StudentQueries.addStudent(student);
        adminStudentStatusLabel.setText(studentFirstName + " " + studentLastName + " " + studentID +  " has been added.");
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_adminStudentSubmitButtonActionPerformed

    private void studentDisplayCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDisplayCoursesButtonActionPerformed
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        studentDisplayCourseTextArea.setText("Course Code\tSeats\tDescription\n");
        for (CourseEntry course:courses){
            studentDisplayCourseTextArea.append(course.getCourseCode() + "\t" + course.getSeats() + "\t" + course.getCourseDescription() + "\n");
                    
        }
        
        
    }//GEN-LAST:event_studentDisplayCoursesButtonActionPerformed

    private void studentDisplayScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDisplayScheduleButtonActionPerformed
        
        studentDisplayScheduleTextArea.setText("");
        String fullName = studentDisplayCourseComboBox.getSelectedItem().toString();
        
        String[] names = fullName.split(" ");
        String id = names[2];
        
        ArrayList<ScheduleEntry> schedules = ScheduleQueries.getScheduleByStudent(currentSemester, id);
        
        studentDisplayScheduleTextArea.setText("Course Code\tStatus\n");
        for (ScheduleEntry entry:schedules){
            studentDisplayScheduleTextArea.append(entry.getCourseCode() + "\t" + entry.getStatus() + "\n");
            
        }
      
        
    }//GEN-LAST:event_studentDisplayScheduleButtonActionPerformed

    private void studentScheduleCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentScheduleCourseButtonActionPerformed
        String courseCode = studentScheduleCourseComboBox1.getSelectedItem().toString();
        
        String fullName = studentScheduleCourseComboBox2.getSelectedItem().toString();
        
        
        String[] names = fullName.split(" ");
        String studentID = names[2];
        
        java.sql.Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        
        int seatsTotal = CourseQueries.getCourseSeats(currentSemester,courseCode);
        int seatsTaken = ScheduleQueries.getScheduledStudentCount(currentSemester, courseCode);
        
        ArrayList<ScheduleEntry> scheduledStudents = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, courseCode);
        for (ScheduleEntry entry:scheduledStudents) 
        {
            
            if (entry.getStudentID().equals(studentID)) 
            {
                studentScheduleCourseStatusLabel.setText(fullName +" has already scheduled this course");
                return;
            }
        }
        if (seatsTotal>seatsTaken)
        {
            ScheduleEntry student = new ScheduleEntry(currentSemester, studentID, courseCode, "s", timestamp);//
            ScheduleQueries.addScheduleEntry(student);
            studentScheduleCourseStatusLabel.setText(studentScheduleCourseComboBox1.getSelectedItem().toString() +" has been scheduled for the current semester.");
            
        }
        else{
            ScheduleEntry student = new ScheduleEntry(currentSemester, studentID, courseCode, "w", timestamp);
            ScheduleQueries.addScheduleEntry(student);
            studentScheduleCourseStatusLabel.setText(studentScheduleCourseComboBox1.getSelectedItem().toString() +" has been waitlisted for the current semester.");
        }
    }//GEN-LAST:event_studentScheduleCourseButtonActionPerformed
    //not needed accidentally added
    private void adminCourseCodeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseCodeTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCourseCodeTextfieldActionPerformed

    private void adminCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseSubmitButtonActionPerformed
        String code = adminCourseCodeTextfield.getText();
        String currSem = currentSemesterLabel2.getText();
        String desc = adminCourseDescriptionTextField.getText();
        int numSeats = (Integer)adminCourseSeatsSpinner.getValue();
        CourseEntry entry = new CourseEntry(currSem,code,desc,numSeats);
        CourseQueries.addCourse(entry);
        adminCourseStatusLabel.setText(code + " has been added");
        adminCourseSeatsSpinner.setValue(0);
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_adminCourseSubmitButtonActionPerformed

    private void adminCourseListDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseListDisplayButtonActionPerformed
        
        String course = adminCourseListComboBox.getSelectedItem().toString();
        String currSem = currentSemesterLabel2.getText();
        ArrayList<ScheduleEntry> scheduledStudents = ScheduleQueries.getScheduledStudentsByCourse(currSem, course);
        ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currSem, course);
        
        
        adminCourseListScheduledTextArea.setText("First Name\tLastName\tStudentID\n");
        adminCourseListWaitlistTextArea.setText("First Name\tLastName\tStudentID\n");
        for (ScheduleEntry entry: scheduledStudents)
        {
            StudentEntry student = StudentQueries.getStudent(entry.getStudentID());
            adminCourseListScheduledTextArea.append(student.getFirstName() + "\t" + student.getLastName() + "\t" + entry.getStudentID() + "\n");
            
        }
        
        for (ScheduleEntry entry: waitlistedStudents)
        {
            StudentEntry student = StudentQueries.getStudent(entry.getStudentID());
            adminCourseListWaitlistTextArea.append(student.getFirstName() + "\t" + student.getLastName() + "\t" + entry.getStudentID() + "\n");
        }
        
        
    }//GEN-LAST:event_adminCourseListDisplayButtonActionPerformed

    private void adminDropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDropStudentButtonActionPerformed
        // TODO add your handling code here:
        String fullName = adminDropStudentComboBox.getSelectedItem().toString();
        String names[] = fullName.split(" ");
        String currStudID = names[2];
        adminDropStudentTextArea.setText("");
        StudentEntry currStudent = StudentQueries.getStudent(currStudID);
        adminDropStudentTextArea.append(adminDropStudentComboBox.getSelectedItem().toString() + " has been dropped from the list of stuents.\n\n"); 

        for (String thisSem : SemesterQueries.getSemesterList())
        {
            
            
            String droppedCourses = "";
            String scheduledCourses = "";
            for (ScheduleEntry currentEntry : ScheduleQueries.getScheduleByStudent(thisSem, currStudent.getStudentID()))
            {
                ScheduleQueries.dropStudentScheduleByCourse(thisSem, currStudent.getStudentID(), currentEntry.getCourseCode());
                droppedCourses += (adminDropStudentComboBox.getSelectedItem().toString() + (currentEntry.getStatus().equals("w") ? " has been dropped from the waitlist for ": " has been dropped from ") + currentEntry.getCourseCode() + "\n");
                
                ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(thisSem, currentEntry.getCourseCode());
                if (!waitlistedStudents.isEmpty())
                {
                    ScheduleQueries.updateScheduleEntry(thisSem, waitlistedStudents.get(0));
                    StudentEntry movedStudent = StudentQueries.getStudent(waitlistedStudents.get(0).getStudentID());
                    scheduledCourses += movedStudent.getLastName() + ", " + movedStudent.getLastName() + " " + waitlistedStudents.get(0).getStudentID() + " has been scheduled into " + waitlistedStudents.get(0).getCourseCode() + "\n";
                }
            }
            if (!droppedCourses.isEmpty() || !scheduledCourses.isEmpty())
            {
                adminDropStudentTextArea.append("For Semester: " + thisSem + "\n");
                adminDropStudentTextArea.append(droppedCourses);
                adminDropStudentTextArea.append(scheduledCourses);
            }
        }
        
        StudentQueries.dropStudent(currStudID);
        rebuildStudentComboBoxes();
       
        
    }//GEN-LAST:event_adminDropStudentButtonActionPerformed

    private void adminDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDropCourseButtonActionPerformed
        
        String cCode = adminDropCourseComboBox.getSelectedItem().toString();
        ArrayList<ScheduleEntry> scheduled = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, cCode);
        ArrayList<ScheduleEntry> waitlisted = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, cCode);
        
        CourseQueries.dropCourse(currentSemester,cCode);
        ScheduleQueries.dropScheduleByCourse(cCode,currentSemester);
        
        adminDropCourseTextArea.setText(cCode + " has been dropped from " + currentSemester + "\n");
        
        
        
        for (ScheduleEntry entry: scheduled) 
        {
            
            StudentEntry student = StudentQueries.getStudent(entry.getStudentID());
            adminDropCourseTextArea.append(student.getFirstName() + " " + student.getLastName() + " " + student.getStudentID() + " has been dropped from " + cCode + "\n" );
        }
        for (ScheduleEntry entry: waitlisted) 
        {
            
            StudentEntry student = StudentQueries.getStudent(entry.getStudentID());
            adminDropCourseTextArea.append(student.getFirstName() + " " + student.getLastName() + " " + student.getStudentID() + " has been dropped from " + cCode + "waitlist\n" );
        }
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_adminDropCourseButtonActionPerformed

    private void studentDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropCourseButtonActionPerformed
        // TODO add your handling code here:
        
        String fullName = studentDropCourseComboBox2.getSelectedItem().toString(); //this isn't right yet
        String[] names = fullName.split(" ");
        String id = names[2];
        
        studentDropCourseTextArea.setText("");
        String dropCourse = studentDropCourseComboBox1.getSelectedItem().toString();
        ScheduleQueries.dropStudentScheduleByCourse(currentSemester, id, dropCourse);
        studentDropCourseTextArea.append(fullName + " has been dropped from " + dropCourse + "\n");
        ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, dropCourse);
        if (!waitlistedStudents.isEmpty())
        {
            ScheduleQueries.updateScheduleEntry(currentSemester, waitlistedStudents.get(0));
            StudentEntry student = StudentQueries.getStudent(waitlistedStudents.get(0).getStudentID());
            studentDropCourseTextArea.append(student.getFirstName() + " " + student.getLastName() + " " + student.getStudentID() + " has been scheduled into " + dropCourse + "\n");
        }
        
        rebuildCourseComboBoxes();
        
        
        //TODO: add students that were enrolled
        
    }//GEN-LAST:event_studentDropCourseButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSchedulerGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminAddCoursePanel;
    private javax.swing.JPanel adminAddSemesterPanel;
    private javax.swing.JPanel adminAddStudentPanel;
    private javax.swing.JLabel adminCourseCodeLabel;
    private javax.swing.JTextField adminCourseCodeTextfield;
    private javax.swing.JLabel adminCourseDescriptionLabel;
    private javax.swing.JTextField adminCourseDescriptionTextField;
    private javax.swing.JComboBox<String> adminCourseListComboBox;
    private javax.swing.JButton adminCourseListDisplayButton;
    private javax.swing.JLabel adminCourseListLabel;
    private javax.swing.JLabel adminCourseListScheduledLabel;
    private javax.swing.JTextArea adminCourseListScheduledTextArea;
    private javax.swing.JLabel adminCourseListWaitlistLabel;
    private javax.swing.JTextArea adminCourseListWaitlistTextArea;
    private javax.swing.JLabel adminCourseSeatsLabel;
    private javax.swing.JSpinner adminCourseSeatsSpinner;
    private javax.swing.JLabel adminCourseStatusLabel;
    private javax.swing.JButton adminCourseSubmitButton;
    private javax.swing.JPanel adminDisplayCourseListPanel;
    private javax.swing.JButton adminDropCourseButton;
    private javax.swing.JComboBox<String> adminDropCourseComboBox;
    private javax.swing.JLabel adminDropCourseLabel;
    private javax.swing.JPanel adminDropCoursePanel;
    private javax.swing.JTextArea adminDropCourseTextArea;
    private javax.swing.JButton adminDropStudentButton;
    private javax.swing.JComboBox<String> adminDropStudentComboBox;
    private javax.swing.JLabel adminDropStudentLabel;
    private javax.swing.JPanel adminDropStudentPanel;
    private javax.swing.JTextArea adminDropStudentTextArea;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminSemesterNameLabel;
    private javax.swing.JTextField adminSemesterNameTextField;
    private javax.swing.JLabel adminSemesterStatusLabel;
    private javax.swing.JButton adminSemesterSubmitButton;
    private javax.swing.JLabel adminStudentFirstNameLabel;
    private javax.swing.JTextField adminStudentFirstNameTextField;
    private javax.swing.JLabel adminStudentIDLabel;
    private javax.swing.JTextField adminStudentIDTextField;
    private javax.swing.JLabel adminStudentLastNameLabel;
    private javax.swing.JTextField adminStudentLastNameTextField;
    private javax.swing.JLabel adminStudentStatusLabel;
    private javax.swing.JButton adminStudentSubmitButton;
    private javax.swing.JTabbedPane adminTabbedPane;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> changeSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel1;
    private javax.swing.JLabel currentSemesterLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JScrollPane studentAddCourseScrollPane;
    private javax.swing.JComboBox<String> studentDisplayCourseComboBox;
    private javax.swing.JLabel studentDisplayCourseLabel;
    private javax.swing.JTextArea studentDisplayCourseTextArea;
    private javax.swing.JButton studentDisplayCoursesButton;
    private javax.swing.JPanel studentDisplayCoursesPanel;
    private javax.swing.JButton studentDisplayScheduleButton;
    private javax.swing.JPanel studentDisplaySchedulePanel;
    private javax.swing.JTextArea studentDisplayScheduleTextArea;
    private javax.swing.JScrollPane studentDisplayScrollPane;
    private javax.swing.JButton studentDropCourseButton;
    private javax.swing.JComboBox<String> studentDropCourseComboBox1;
    private javax.swing.JComboBox<String> studentDropCourseComboBox2;
    private javax.swing.JLabel studentDropCourseLabel1;
    private javax.swing.JLabel studentDropCourseLabel2;
    private javax.swing.JPanel studentDropCoursePanel;
    private javax.swing.JTextArea studentDropCourseTextArea;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JButton studentScheduleCourseButton;
    private javax.swing.JComboBox<String> studentScheduleCourseComboBox1;
    private javax.swing.JComboBox<String> studentScheduleCourseComboBox2;
    private javax.swing.JLabel studentScheduleCourseLabel;
    private javax.swing.JLabel studentScheduleCourseStatusLabel;
    private javax.swing.JLabel studentScheduleCourseStudentLable;
    private javax.swing.JPanel studentScheduleCoursesPanel;
    private javax.swing.JTabbedPane studentTabbedPane;
    // End of variables declaration//GEN-END:variables
}
